//using NoSqlRepositories.Core;
//using NoSqlRepositories.Core;
//using System;
//using System.Collections.Generic;
//using System.IO;
//using System.Linq.Expressions;

//namespace NoSqlRepositories.AzureDocumentDb.Net
//{
//    public class AzureDocumentDbRepository<T> : INoSQLRepository<T> where T : class, IBaseEntity
//    {
//        #region private fields

//        private readonly string connectionString;
//        public string TypeName { get; set; }

//        #endregion

//        #region Constructor

//        public AzureDocumentDbRepository()
//        {

//        }

//        public AzureDocumentDbRepository(string connectionString)
//        {
//            if (string.IsNullOrWhiteSpace(connectionString))
//                throw new ArgumentNullException();

//            this.connectionString = connectionString;

//            TypeName = typeof(T).Name;
//        }

//        #endregion

//        public bool AutoGeneratedEntityDate
//        {
//            get
//            {
//                throw new NotImplementedException();
//            }

//            set
//            {
//                throw new NotImplementedException();
//            }
//        }

//        public void AddAttachment(string id, string filePathAttachment, string contentType, string attachmentName)
//        {
//            throw new NotImplementedException();
//        }

//        public bool CollectionExists(bool createIfNotExists)
//        {
//            throw new NotImplementedException();
//        }

//        public long Delete(string id)
//        {
//            throw new NotImplementedException();
//        }

//        public long Delete(string id, bool physical)
//        {
//            throw new NotImplementedException();
//        }

//        public void DropCollection()
//        {
//            throw new NotImplementedException();
//        }

//        public bool Exist(string id)
//        {
//            throw new NotImplementedException();
//        }

//        public IEnumerable<T> GetAll()
//        {
//            throw new NotImplementedException();
//        }

//        public Stream GetAttachment(string id, string attachmentName)
//        {
//            throw new NotImplementedException();
//        }

//        public IEnumerable<string> GetAttachmentNames(string id)
//        {
//            throw new NotImplementedException();
//        }

//        public T GetById(string id)
//        {
//            throw new NotImplementedException();
//        }

//        public string GetCollectionName()
//        {
//            throw new NotImplementedException();
//        }

//        public void InitCollection()
//        {
//            throw new NotImplementedException();
//        }

//        public void InitCollection(List<Expression<Func<T, object>>> indexFieldSelectors)
//        {
//            throw new NotImplementedException();
//        }

//        public BulkInsertResult<string> InsertMany(IEnumerable<T> entities)
//        {
//            throw new NotImplementedException();
//        }

//        public BulkInsertResult<string> InsertMany(IEnumerable<T> entities, InsertMode insertMode)
//        {
//            throw new NotImplementedException();
//        }

//        public InsertResult InsertOne(T entity)
//        {
//            throw new NotImplementedException();
//        }

//        public InsertResult InsertOne(T entity, InsertMode insertMode)
//        {
//            throw new NotImplementedException();
//        }

//        public void RemoveAttachment(string id, string attachmentName)
//        {
//            throw new NotImplementedException();
//        }

//        public void SetCollectionName(string typeName)
//        {
//            throw new NotImplementedException();
//        }

//        public long TruncateCollection()
//        {
//            throw new NotImplementedException();
//        }

//        public T TryGetById(string id)
//        {
//            throw new NotImplementedException();
//        }

//        public UpdateResult Update(T entity)
//        {
//            throw new NotImplementedException();
//        }

//        public UpdateResult Update(T entity, UpdateMode updateMode)
//        {
//            throw new NotImplementedException();
//        }

//        public void UseDatabase(string dbName)
//        {
//            throw new NotImplementedException();
//        }
//    }
//}
