using MvvmCross.Plugins.File;
using Newtonsoft.Json;
using NoSqlRepositories.Core;
using NoSqlRepositories.Core.Helpers;
using NoSqlRepositories.Core.NoSQLException;
using NoSqlRepositories.MvvX.JsonFiles.Pcl.Helpers;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using NoSqlRepositories.Core.Queries;
using System.Threading.Tasks;

namespace NoSqlRepositories.MvvX.JsonFiles.Pcl
{
    public class JsonFileRepository<T> : RepositoryBase<T> where T : class, IBaseEntity
    {
        #region Members
        
        public override string DatabaseName
        {
            get
            {
                return dBName;
            }
        }

        public override NoSQLEngineType EngineType
        {
            get
            {
                return NoSQLEngineType.JsonFile;
            }
        }

        private readonly IMvxFileStore fileStore;

        private string dBName { get; set; }

        private string AttachmentsDirectoryPath
        {
            get
            {
                return dBName + "/Attachments/" + CollectionName;
            }
        }

        private string DbDirectoryPath
        {
            get
            {
                return dBName;
            }
        }

        public string DbFilePath
        {
            get
            {
                return dBName + "/" + CollectionName + ".json";
            }
        }

        public string DbConfigFilePath
        {
            get
            {
                return dBName + "/" + CollectionName + ".config.json";
            }
        }

        private IDictionary<string, T> localDb;
        private DbConfiguration config;

        #endregion

        public JsonFileRepository(IMvxFileStore fileStore, string dbName)
        {
            if (fileStore == null)
                throw new ArgumentNullException("fileStore");

            this.fileStore = fileStore;
            this.dBName = dbName;

            CollectionName = typeof(T).Name;
            LoadJSONFile();

            ConnectAgainToDatabase = () => LoadJSONFile();
        }

        #region INoSQLRepository

        public override async Task Close()
        {
            SaveJSONFile();
            ConnectionOpened = false;
        }

        public override void ConnectAgain()
        {
            ConnectAgainToDatabase();
        }

        public override T GetById(string id)
        {
            CheckOpenedConnection();

            T elt;

            if (!localDb.TryGetValue(id, out elt))
            {
                throw new KeyNotFoundNoSQLException(string.Format("Id '{0}' not found in the repository '{1}'", id, DbFilePath));
            }

            if (elt.Deleted)
            {
                throw new KeyNotFoundNoSQLException(string.Format("Id '{0}' not found in the repository '{1}'", id, DbFilePath));
            }

            if (config.IsExpired(id))
            {
                throw new KeyNotFoundNoSQLException(string.Format("Id '{0}' not found in the repository '{1}'", id, DbFilePath));
            }

            return elt;
        }

        public override IList<T> GetByIds(IList<string> ids)
        {
            CheckOpenedConnection();

            IList<T> elts = new List<T>();

            foreach (string id in ids)
            {
                var elt = TryGetById(id);
                if (elt != null)
                    elts.Add(elt);
            }

            return elts;
        }

        public override InsertResult InsertOne(T entity, InsertMode keyExistsAction)
        {
            CheckOpenedConnection();

            var insertResult = default(InsertResult);

            var date = NoSQLRepoHelper.DateTimeUtcNow();
            if (AutoGeneratedEntityDate)
            {
                entity.SystemCreationDate = date;
                entity.SystemLastUpdateDate = date;
            }

            NoSQLRepoHelper.SetIds(entity);

            if (localDb.ContainsKey(entity.Id))
            {
                if (keyExistsAction == InsertMode.error_if_key_exists)
                {
                    throw new DupplicateKeyNoSQLException();
                }
                else if (keyExistsAction == InsertMode.do_nothing_if_key_exists)
                {
                    return InsertResult.not_affected;
                }
                else if (keyExistsAction == InsertMode.erase_existing)
                {
                    entity.SystemCreationDate = localDb[entity.Id].SystemCreationDate; // keep the origin creation date of the entity
                    // Continue execution
                }
                insertResult = InsertResult.updated;
            }
            else
            {
                insertResult = InsertResult.inserted;
            }

            // Clone to not shared reference between App instance and repository persisted value
            // UTC : Ensure to store only utc datetime
            var entityToStore = NewtonJsonHelper.CloneJson(entity, DateTimeZoneHandling.Utc);

            localDb[entity.Id] = entityToStore;
            config.ExpireAt(entity.Id, null);

            SaveJSONFile();
            return insertResult;
        }

        public override BulkInsertResult<string> InsertMany(IEnumerable<T> entities, InsertMode insertMode)
        {
            CheckOpenedConnection();

            if (insertMode != InsertMode.db_implementation)
                throw new NotImplementedException();

            var insertResult = new BulkInsertResult<string>();

            var creationDate = NoSQLRepoHelper.DateTimeUtcNow();

            foreach (var entity in entities)
            {
                if (AutoGeneratedEntityDate)
                    entity.SystemCreationDate = creationDate;
                if (AutoGeneratedEntityDate)
                    entity.SystemLastUpdateDate = creationDate;

                NoSQLRepoHelper.SetIds(entity);

                var entityToStore = NewtonJsonHelper.CloneJson(entity, DateTimeZoneHandling.Utc);
                localDb[entity.Id] = entityToStore;
                config.ExpireAt(entity.Id, null);
                insertResult[entity.Id] = InsertResult.unknown;
            }
            SaveJSONFile();

            return insertResult;
        }

        public override bool Exist(string id)
        {
            CheckOpenedConnection();

            return localDb.ContainsKey(id);
        }

        public override UpdateResult Update(T entity, UpdateMode updateMode)
        {
            CheckOpenedConnection();

            var updateResult = default(UpdateResult);

            if (updateMode == UpdateMode.upsert_if_missing_key)
            {
                throw new NotImplementedException();
            }

            var updateDate = NoSQLRepoHelper.DateTimeUtcNow();

            entity.SystemLastUpdateDate = updateDate;

            if (updateMode == UpdateMode.upsert_if_missing_key)
            {
                NoSQLRepoHelper.SetIds(entity);
                entity.SystemCreationDate = updateDate;
            }

            if (!localDb.ContainsKey(entity.Id))
            {
                if (updateMode == UpdateMode.error_if_missing_key)
                {
                    throw new KeyNotFoundNoSQLException("Misssing key '" + entity.Id + "'");
                }
                else if (updateMode == UpdateMode.do_nothing_if_missing_key)
                {
                    return UpdateResult.not_affected;
                }

                updateResult = UpdateResult.inserted;
            }

            localDb[entity.Id] = entity;

            SaveJSONFile();
            updateResult = UpdateResult.updated;

            return updateResult;
        }

        public override long Delete(string id, bool physical)
        {
            CheckOpenedConnection();

            if (localDb.ContainsKey(id))
            {
                foreach (var attachmentName in GetAttachmentNames(id))
                {
                    RemoveAttachment(id, attachmentName);
                }

                if (physical)
                {
                    localDb.Remove(id);
                    config.Delete(id);
                }
                else
                {
                    localDb[id].Deleted = true;
                }
                SaveJSONFile();
                return 1;
            }
            else
            {
                return 0;
            }
        }

        public override T TryGetById(string id)
        {
            CheckOpenedConnection();

            T res;

            try
            {
                res = GetById(id);
            }
            catch (KeyNotFoundNoSQLException)
            {
                res = default(T);
            }
            return res;
        }

        public override void InitCollection(IList<Expression<Func<T, object>>> indexFieldSelectors)
        {
            CheckOpenedConnection();

            // Nothing to do to initialize the collection
        }

        public override int Count()
        {
            CheckOpenedConnection();

            if (this.localDb != null)
            {
                return localDb.Values.Count(e => !config.IsExpired(e.Id));
            }

            return 0;
        }

        #endregion

        #region INoSQLDB

        public override void ExpireAt(string id, DateTime? dateLimit)
        {
            CheckOpenedConnection();

            config.ExpireAt(id, dateLimit);
            SavedDbConfig();
        }

        public override bool CompactDatabase()
        {
            CheckOpenedConnection();

            if (this.localDb != null)
            {
                foreach (var item in localDb.Values.Where(e => e.Deleted || config.IsExpired(e.Id)))
                {
                    Delete(item.Id, true);
                }
            }
            return true;
        }

        public override long TruncateCollection()
        {
            CheckOpenedConnection();

            var count = localDb.Keys.Count;
            localDb = new ConcurrentDictionary<string, T>();
            config.Compact();
            SaveJSONFile();
            return count;
        }

        public override void SetCollectionName(string typeName)
        {
            CheckOpenedConnection();

            CollectionName = typeName;
            LoadJSONFile();
        }

        public override void InitCollection()
        {
            CheckOpenedConnection();

            // Autoinit, nothing to do
        }

        public override void UseDatabase(string dbName)
        {
            CheckOpenedConnection();

            throw new NotImplementedException();
        }

        public override bool CollectionExists(bool createIfNotExists)
        {
            CheckOpenedConnection();

            throw new NotImplementedException();
        }

        public override void DropCollection()
        {
            CheckOpenedConnection();

            this.localDb = new Dictionary<string, T>();
            config.Compact();
            SaveJSONFile();
        }

        #endregion

        #region Private methods

        private void LoadJSONFile()
        {
            //if (File.Exists(DbFilePath))
            if (fileStore.Exists(DbFilePath))
            {
                string content = null;
                if (fileStore.TryReadTextFile(DbFilePath, out content))
                {
                    var settings = new JsonSerializerSettings()
                    {
                        TypeNameHandling = TypeNameHandling.Objects,
                        DefaultValueHandling = DefaultValueHandling.Populate
                    };

                    this.localDb = JsonConvert.DeserializeObject<IDictionary<string, T>>(content, settings);

                    if (this.localDb == null)
                        this.localDb = new ConcurrentDictionary<string, T>(); // Empty file
                }
                else
                {
                    throw new IOException(string.Format("Cannot read json repository file '{0}'", DbFilePath));
                }
            }
            else
            {
                this.localDb = new Dictionary<string, T>();
            }
            LoadDbConfigFile();

            ConnectionOpened = true;
        }

        private void SaveJSONFile()
        {
            var settings = new JsonSerializerSettings()
            {
                TypeNameHandling = TypeNameHandling.Auto,
                NullValueHandling = NullValueHandling.Ignore,
                DefaultValueHandling = DefaultValueHandling.Ignore,
                // TypeNameAssemblyFormat = System.Runtime.Serialization.Formatters.FormatterAssemblyStyle.Simple
            };

            string content = JsonConvert.SerializeObject(this.localDb, Formatting.Indented, settings);
            fileStore.EnsureFolderExists(DbDirectoryPath);
            fileStore.WriteFile(DbFilePath, content);

            SavedDbConfig();
        }
        
        private void LoadDbConfigFile()
        {
            if (fileStore.Exists(DbConfigFilePath))
            {
                string content = null;
                if (fileStore.TryReadTextFile(DbConfigFilePath, out content))
                {
                        var settings = new JsonSerializerSettings()
                    {
                        TypeNameHandling = TypeNameHandling.Objects,
                        DefaultValueHandling = DefaultValueHandling.Populate
                    };

                    this.config = JsonConvert.DeserializeObject<DbConfiguration>(content, settings);

                    if (this.config == null)
                        this.config = new DbConfiguration(); // Empty file
                }
            }
            else
            {
                this.config = new DbConfiguration();
            }
        }

        private void SavedDbConfig()
        {
            var settings = new JsonSerializerSettings()
            {
                TypeNameHandling = TypeNameHandling.Auto,
                NullValueHandling = NullValueHandling.Ignore,
                DefaultValueHandling = DefaultValueHandling.Ignore
            };

            string content = JsonConvert.SerializeObject(this.config, Formatting.Indented, settings);
            fileStore.EnsureFolderExists(DbDirectoryPath);
            fileStore.WriteFile(DbConfigFilePath, content);
        }

        #endregion

        #region Attachments

        public override void AddAttachment(string id, Stream fileStream, string contentType, string attachmentName)
        {
            CheckOpenedConnection();

            var entityAttachmentDir = fileStore.PathCombine(AttachmentsDirectoryPath, id);
            var attachmentFilePath = fileStore.PathCombine(entityAttachmentDir, attachmentName);
            fileStore.EnsureFolderExists(entityAttachmentDir);

            fileStore.WriteFile(attachmentFilePath, (localFileStream) => fileStream.CopyTo(localFileStream));
        }

        public override void RemoveAttachment(string id, string attachmentName)
        {
            CheckOpenedConnection();

            var entityAttachmentDir = AttachmentsDirectoryPath + "/" + id;
            var attachmentFilePath = entityAttachmentDir + "/" + attachmentName;

            if (!Exist(id))
                throw new KeyNotFoundNoSQLException();

            if (!fileStore.Exists(attachmentFilePath))
                throw new AttachmentNotFoundNoSQLException();

            fileStore.DeleteFile(attachmentFilePath);
        }

        public override Stream GetAttachment(string id, string attachmentName)
        {
            CheckOpenedConnection();

            var entityAttachmentDir = AttachmentsDirectoryPath + "/" + id;
            var attachmentFilePath = entityAttachmentDir + "/" + attachmentName;

            if (!Exist(id))
                throw new KeyNotFoundNoSQLException();

            if (!fileStore.Exists(attachmentFilePath))
                throw new AttachmentNotFoundNoSQLException();

            return fileStore.OpenRead(attachmentFilePath);
        }

        /// <summary>
        /// Return all entities of repository
        /// </summary>
        /// <returns></returns>
        public override IEnumerable<T> GetAll()
        {
            CheckOpenedConnection();

            if (this.localDb != null)
            {
                return localDb.Values.Where(e => !config.IsExpired(e.Id));
            }

            return new List<T>();
        }

        /// <summary>
        /// Return the list of name of all attachements of a given entity
        /// </summary>
        /// <param name="idDocument"></param>
        /// <returns></returns>
        public override IEnumerable<string> GetAttachmentNames(string idDocument)
        {
            CheckOpenedConnection();

            var entityAttachmentDir = fileStore.PathCombine(AttachmentsDirectoryPath, idDocument);

            if (fileStore.FolderExists(entityAttachmentDir))
            {
                var fullFilePath = fileStore.GetFilesIn(entityAttachmentDir);
                return fullFilePath.Select(file => file.Substring(file.LastIndexOf("\\", StringComparison.Ordinal) + 1));
            }
            return new List<string>();
        }

        public override IEnumerable<T> GetByField<TField>(string fieldName, List<TField> values)
        {
            CheckOpenedConnection();

            throw new NotImplementedException();
        }

        public override IEnumerable<T> GetByField<TField>(string fieldName, TField value)
        {
            CheckOpenedConnection();

            throw new NotImplementedException();
        }

        public override IEnumerable<string> GetKeyByField<TField>(string fieldName, List<TField> values)
        {
            CheckOpenedConnection();

            throw new NotImplementedException();
        }

        public override IEnumerable<string> GetKeyByField<TField>(string fieldName, TField value)
        {
            CheckOpenedConnection();

            throw new NotImplementedException();
        }

        #endregion

        #region Queries

        public override IEnumerable<T> DoQuery(NoSqlQuery<T> queryFilters)
        {
            CheckOpenedConnection();

            if (this.localDb != null)
            {
                var resultQuery = localDb.Values.Where(e => !config.IsExpired(e.Id));

                if (queryFilters.PostFilter != null)
                    resultQuery = resultQuery.Where(e => queryFilters.PostFilter(e));
                if (queryFilters.Skip != 0)
                    resultQuery = resultQuery.Skip(queryFilters.Skip);
                if (queryFilters.Limit != 0)
                    resultQuery = resultQuery.Take(queryFilters.Limit);

                return resultQuery;
            }

            return new List<T>();
        }

        #endregion
    }
}
